server:
  port: 8001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://MASTER:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
              - Path=/v1/auth/**
          filters:
              #            - AddRequestHeader=first-request, first-request-header-yml
              #            - AddResponseHeader=first-response, first-response-header-yml
              - CustomFilter
          
       
