server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://MASTER:8761/eureka

  cloud:
    gateway:
      mvc:
        routes:
          - id: auth
            uri: http://SN01:8080/
            predicates:
                - Path=/v1/**
            filters:
                #            - AddRequestHeader=first-request, first-request-header-yml
                #            - AddResponseHeader=first-response, first-response-header-yml
                - CustomFilter
          
       
