server:
  port: 8001

eureka:
  client:
    registry-fetch-interval-seconds: 10
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://MASTER:8761/eureka

spring:
  cloud:
      gateway:
        mvc:
          routes:
            - id: auth
              uri: lb://AUTH
              predicates:
                  - Path=/v1/auth/**
       
