server:
    port: 8084

spring:
    application:
        name: user
    datasource:
        url: jdbc:mysql://MASKING_URL
        username: MAKING_USERNAME
        password: MASKING_PASSWORD
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    mail:
        username: MAKSING_EMAIL
        password: MASKING_PASSWORD
        host: MASKING_SMTP
        port: 587
        properties:
            debug: true
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
            mime:
                charset: UTF-8
            transport:
                protocol: smtp
    cloud:
        openfeign:
            okhttp:
                enabled: true
cloud:
    aws:
        s3:
            bucket: wp-ht-s3
        credentials:
            access-key: MASKING_KEY
            secret-key: MASKING_SECRET
        region:
            static: ap-northeast-2
            auto: false
        stack:
            auto: false

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

eureka:
    instance:
        disable-delta: true
        instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
        lease-renewal-interval-in-seconds: 3
        lease-expiration-duration-in-seconds: 10
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://MASTER:8761/eureka/

redis:
    master:
        host: MASTER
        port: 6379
    nodes:
        - host: SN01
          port: 6379
        - host: SN02
          port: 6379
    password: MASKING_PASSWORD
