spring:
  port: 8000
  ssl:
    key-store: src/main/resources/AN-keystore.p12
    key-store-type: PKCS12
    key-store-password: asdf134620!
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:http://MASTER:8888
  cloud:
    gateway:
