server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  server:
    response-cache-update-interval-ms: 3000
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
