server:
  port: 8762

spring:
  application:
    name: discoveryservice

eureka:
  instance:
    hostname: 172.30.1.50
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
