server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles: # profiles 설정
    active: local # 다른 설정이 없을 때 default 환경 값