spring:
  datasource:
    url: jdbc:mysql://kpc.chf1yiylcr3s.ap-northeast-2.rds.amazonaws.com:3306/wp?serverTimezone=UTC
    username: kpc
    password: asdf134620!
  data:
    redis:
      host: i10a501.p.ssafy.io
      port: 6379
  kafka:
    bootstrap-servers: http://i10a501.p.ssafy.io:9092
    template:
      default-topic: chat
    consumer:
      group-id: ${random.uuid}
