spring:
  application:
    name: user
  profiles:
    active: dev
  config:
    import: optional:configserver:http://MASTER:8888
    spring.clo
cloud:
  aws:
    s3:
      bucket: wp
    credentials:
      access-key: