spring:
  datasource:
    url: jdbc:mysql://kpc.chf1yiylcr3s.ap-northeast-2.rds.amazonaws.com:3306/wp?serverTimezone=UTC
    username: kpc
    password: asdf134620!
  mail:
    username: hyeseung2000@gmail.com
    password: tcorfahrykuyffgx

cloud:
  aws:
    s3:
      bucket: wp-ht-s3
    credentials:
      access-key: AKIA4MDWI2KWXGRMYXSC
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false