server:
    port: 8083

spring:
    application:
        name: broadcast
    datasource:
        url: jdbc:mysql://MASKING_URL
        username: MAKING_USERNAME
        password: MASKING_PASSWORD
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

auth:
    url: MASKING_URL

mediate:
    url: MASKING_URL:8081

user:
    url: MASKING_URL

redis:
    master:
        host: SN01
        port: 6379
    nodes:
        - host: SN02
          port: 6379
        - host: SN03
          port: 6379
    password: MSKING_PASSWORD
eureka:
    instance:
        disable-delta: true
        instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
        lease-renewal-interval-in-seconds: 3
        lease-expiration-duration-in-seconds: 10
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://MASTER:8761/eureka/
