server:
  port: 8083

spring:
  application:
    name: analyze
  datasource:
    url: jdbc:mysql://MASKING_URL/wp?serverTimezone=UTC
    username: MASKING_USERNAME
    password: MASKING_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

openvidu:
  url: MASKING_URL
  password: MASKING_PASSWORD

redis:
  master:
    host: MASKING_URL
    port: 6379
  nodes:
    - host: MASKING_URL
      port: 6379
  password: MASKING_PASSWORD
