server:
    port: 8086

spring:
    application:
        name: chatbot
    datasource:
        url: jdbc:mysql://MASKING_URL
        username: MAKING_USERNAME
        password: MASKING_PASSWORD
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                ddl-auto: create
                format_sql: true
                show_sql: true
    elastic:
        url: MASKING_URL:9200
    thymeleaf:
        prefix: classpath:/templates/
        check-template-location: true
        suffix: .html
        mode: HTML

logging.level:
    org.hibernate.orm.jdbc.bind: trace
    org:
        springframework:
            data:
                elasticsearch:
                    client: DEBUG

eureka:
    instance:
        disable-delta: true
        instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
        lease-renewal-interval-in-seconds: 3
        lease-expiration-duration-in-seconds: 10
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://MASTER:8761/eureka/
