server:
  port: 8083

spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://kpc.chf1yiylcr3s.ap-northeast-2.rds.amazonaws.com:3306/wp?serverTimezone=UTC
    username: kpc
    password: asdf134620!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

auth:
  url: http://172.30.1.50:8000

mediate:
  url: http://3.39.6.29:8081

redis:
  master:
    host: 172.30.1.51
    port: 6379
  nodes:
    - host: 172.30.1.52
      port: 6379
    - host: 172.30.1.53
      port: 6379
  password: asdf134620!

  eureka:
  instance:
    disable-delta: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://MASTER:8761/eureka/
